server:
  port: 8083
  contextPath: /
  address: 0.0.0.0

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tcc_order?useUnicode=true&characterEncoding=utf8
        username: root
        password: root

mybatis:
  type-aliases-package: com.hmily.tcc.demo.dubbo.order.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: debug
        org.springframework.web: info
        org.apache.ibatis: info
        com.hmily.bonuspoint: debug
        com.hmily.lottery: debug
        com.hmily: debug
        io.netty: info

    path: "./logs"

